---
title: Dotplot 
author: "pz"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    highlight: tango
    df_print: paged
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
    code_folding: hide
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, result='hold',fig.width=8,tidy=TRUE, cache=FALSE)
knitr::opts_knit$set(progress=TRUE,verbose=TRUE)
```

```{r libraries, cache=FALSE}
library(data.table)
library(magrittr)
library(knitr)
library(ggplot2); theme_set(theme_bw(base_size = 16))
library(DESeq2)
library(ggsci)
library(dplyr)
library(pheatmap)
library(openxlsx)
library(ggrepel)
```




```{r decoder}
# OM5267
decoderFile1 <- "OM5267_naive_decoder.txt"
decoder.data1 <- fread(decoderFile1) %>% as.data.frame()
decoder.data1$sample.ID = paste0(decoder.data1$RUN_ID,"_",decoder.data1$SAMPLE_ID)
row.names(decoder.data1) = decoder.data1$sample.ID

# OM5220
decoderFile2 <- "OM5220_naive_decoder.txt"
decoder.data2 <- fread(decoderFile2) %>% as.data.frame()
decoder.data2$sample.ID = paste0(decoder.data2$RUN_ID,"_",decoder.data2$SAMPLE_ID)
row.names(decoder.data2) = decoder.data2$sample.ID

# Combine
decoder.data <- rbind(decoder.data1, decoder.data2)
decoder.data$HIV <- factor(decoder.data$HIV)
decoder.data$CTL <- factor(decoder.data$CTL)
decoder.data$DONOR = factor(decoder.data$DONOR)
decoder.data = decoder.data[order(decoder.data$CTL, decoder.data$HIV,decoder.data$DONOR),]
decoder.data$group = factor(decoder.data$group)
```


```{r counts}
# OM5267
counts1 <- read.csv(file = "OM5267_gene_counts.txt", header = TRUE, check.names=FALSE, row.names=1)
decoder.data1 <- decoder.data1[decoder.data1$sample.ID %in% colnames(counts1),]

# OM5220
counts2 <- read.csv(file = "OM5220_gene_counts.txt", header = TRUE, check.names=FALSE, row.names=1)
decoder.data2 <- decoder.data2[decoder.data2$sample.ID %in% colnames(counts2),]

# Combine
counts <- cbind(counts1, counts2)
counts <- counts[,c(decoder.data$sample.ID)]

if (!identical(colnames(counts), decoder.data$sample.ID)) {
  stop("Column names in counts do not match sample IDs in decoder data")
}
```

# Samples

The following samples were part of this analysis:

```{r samples}
as_tibble(decoder.data[,c("sample.ID", "HIV", "CTL", "group")])
```


## Gene(s) of interest

```{r createDDS}
dds <- DESeq2::DESeqDataSetFromMatrix(countData = counts, 
                                      colData = decoder.data, 
                                      design = ~ DONOR + HIV * CTL)

keep <- edgeR::filterByExpr(counts(dds), design = model.matrix(~ DONOR + HIV * CTL, data = colData(dds)))
dds <- dds[keep,]
dds <- estimateSizeFactors(dds)
vsd <- DESeq2::vst(dds, blind = TRUE)
normCounts = assay(vsd)
```



## VS-transformed, facet

```{r dotplot_bothNaive_vst_facet, fig.height = 3.5, fig.width = 6, results="asis",  fig.path='EZH2_dotplots/',  dev=c('png','pdf')}
goi = c("EZH2")

cols <- c("#4DBBD5FF", "#E64B35FF") 

lapply(goi, function(y){
  cat("\n\n###",y, "\n\n")
  vst.df <- assay(vsd[y,]) %>% reshape2::melt(., id.vars = rownames)
  names(vst.df) <- c("gene","sample","exprs")
  vst.df = merge(vst.df, decoder.data, by.x="sample", by.y="sample.ID")
  vst.df$group = factor(vst.df$group) 
  p1 =   ggplot(vst.df, aes(x=CTL, y=exprs)) +
  geom_point(position=position_dodge(width=0.75),aes(color=HIV, group=interaction(CTL,HIV)), size=2) +
      scale_color_manual(values = cols, name = "HIV") + 
    scale_shape_manual(values = c(16, 17)) +
    theme_minimal(base_size = 16,) + 
    theme(legend.position = "right") +
    labs(x = "CTL",y = expression("Log"[2]*" Norm. Count"), title = y) +
    facet_wrap(~DONOR, scales="free") +  
    theme( axis.line = element_line(size = 0.4, colour = "black", linetype=1))
    print(p1)
}) %>%  invisible()
     
```



# Session Info
```{r session, message=FALSE, warning=FALSE, cache=FALSE,echo=FALSE, fig.width=10, fig.height=5.5, context="data"}
sessionInfo()
```